
name: Report Server Build Dev
on:
  push:


concurrency:
  cancel-in-progress: true
  group: report-server-build-app

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION : "us-east-1"
  ECR_REPO_ADDRESS: 917902836630.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPO: 917902836630.dkr.ecr.us-east-1.amazonaws.com/report-server


jobs:
  App_Build:
    name: Docker Build and Push
    uses: ./.github/workflows/build_push.yaml
    with:
      repo-name: test-repo

