
name: Create Release Candidate
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  cancel-in-progress: true
  group: report-server-build-app-rc

jobs:
  Define_Tag:
    runs-on: ubuntu-latest
    outputs:
      tag_value: ${{ steps.tag.outputs.tag_value }}
    steps:
      - name: Define Tag Name
        id: tag
        run: |
          branch=$(echo ${GITHUB_REF##*/})
          if [[ $branch == 'release/'* ]]; then
            RELEASE=$(echo $branch | cut -d'/' -f2)
            echo "tag_value=$RELEASE-rc-build" >> $GITHUB_OUTPUT
          else
            echo "Branch don't match release pattern."
            exit 1
          fi

  App_Build:
    name: Release Candidate
    uses: ./.github/workflows/build_push.yaml
    needs: Define_Tag
    with:
      repo-name: test-repo
      tag: ${{ needs.Define_Tag.outputs.tag_value }}
