
name: Report Server Build Dev
on:
  workflow_dispatch: {}
  push:
    branches:
      - dev


concurrency:
  cancel-in-progress: true
  group: report-server-build-app

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION : "us-east-1"
  ECR_REPO_ADDRESS: 917902836630.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPO: 917902836630.dkr.ecr.us-east-1.amazonaws.com/report-server


jobs:
  App_Build:
    name: Docker Build and Push
    uses: ./.github/workflows/build_push.yaml
    with:
      repo-name: test-repo
      tag: dev

  Deploy:
    needs: App_Build
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::017925157769:role/cmiml-dev-oidc-github-role
          role-session-name: OIDC-GHA-session
          aws-region: us-east-1

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition report_server --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: report_server
          image: ${{ needs.App_Build.outputs.image }}

      - name: Update Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: report-server
          cluster: cmiml-dev
          wait-for-service-stability: true