
name: Create Release Candidate
on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

concurrency:
  cancel-in-progress: true
  group: report-server-build-app-rc

jobs:
  Define_Tag:
    runs-on: ubuntu-latest
    if: github.ref == 'release/*'
    outputs:
      image_name: ${{ steps.tag.outputs.image_name }}
    steps:
      - name: Define Tag Name
        id: tag
        run: |
          RELEASE=$(echo {{ github.ref }} | cut -d'/' -f2)
          echo "image_name=${ECR_REPO}:RELEASE-rc-build-${SHORT_SHA}" >> $GITHUB_OUTPUT

  App_Build:
    name: Release Candidate
    uses: ./.github/workflows/build_push.yaml
    needs: Define_Tag
    with:
      repo-name: test-repo
      tag: ${{ needs.Define_Tag.outputs.image_name }}
