
name: Create Production Release
on:
  workflow_dispatch: {}
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main

permissions:
  id-token: write
  contents: write

concurrency:
  cancel-in-progress: true
  group: report-server-build-app-prod

jobs:
  Allow_Run:
    #if: github.event.pull_request.merged == true
    if: github.event.pull_request.merged == true && (contains(toJSON(github.event.pull_request.head.ref), 'release/') || contains(toJSON(github.event.pull_request.head.ref), 'hotfix/'))

    runs-on: ubuntu-latest
    steps:
      - name: Check Branch
        run: |
          if [[ echo '${{ github.event.pull_request.head.ref }}' | grep -E -e '-rc[0-9]+' ]]; then
            echo "Branch does not match production branch pattern."
            exit 1
          else
            echo "Branch is valid to deploy a production image. Proceeding ..."
          fi
#        run: |
#          if [[ ${{ github.event.pull_request.head.ref }} == 'release/'* ]]; then
#            echo "Branch is valid to deploy a production image. Proceeding ..."
#          else
#            echo "Branch don't match production branch pattern."
#            exit 1
#          fi
